force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>A collection of answerable questions related to a Program Engagement, based on an Application Template associated with the Contact&apos;s Program Cohort</description>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Application_Template__c.field-meta.xml
<CustomField>
    <fullName>Application_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Template</label>
    <referenceTo>Application_Template__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Program_Engagement__c.field-meta.xml
<CustomField>
    <fullName>Program_Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Engagement</label>
    <referenceTo>pmdm__ProgramEngagement__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Answer__c/Application_Answer__c.object-meta.xml
<CustomObject>
    <description>An answer to an individual Question in an Application</description>
    <label>Application Answer</label>
    <nameField>
        <displayFormat>ANS-{0000000}</displayFormat>
        <label>Application Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Answer__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Answers</relationshipLabel>
    <relationshipName>Application_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Application_Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>The question prompt that the applicant responded to</description>
    <inlineHelpText>The question prompt that the applicant responded to</inlineHelpText>
    <label>Question</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Answer__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>The order in which this question/answer appears when presented on an application. Inherited from the Application Template Question that generated the Application Answer record. Lowest values appear first.</description>
    <inlineHelpText>The order in which this question/answer appears when presented on an application. Lowest values appear first.</inlineHelpText>
    <label>Sort Order</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application_Answer__c/fields/Source_Question__c.field-meta.xml
<CustomField>
    <fullName>Source_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Application Answers</relationshipLabel>
    <relationshipName>Application_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application_Template__c/Application_Template__c.object-meta.xml
<CustomObject>
    <description>A grouping of Questions to be filled out in a single Application</description>
    <label>Application Template</label>
    <nameField>
        <label>Application Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>An individual question asked in an Application. Can be associated with one or many Application Templates.</description>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Type__c</fullName>
    <description>The field type of the question determines its properties and display when presented in an Application</description>
    <inlineHelpText>The field type of the question determines its properties and display when presented in an Application</inlineHelpText>
    <label>Field Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Multiple Choice</fullName>
            </value>
            <value>
                <fullName>Long Text Area</fullName>
            </value>
            <value>
                <fullName>File Upload</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Help_Text__c</fullName>
    <description>Help Text to present to the applicant when encountering this field in an Application</description>
    <inlineHelpText>Help Text to present to the applicant when encountering this field in an Application</inlineHelpText>
    <label>Help Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Max_Selectable_Options__c.field-meta.xml
<CustomField>
    <fullName>Max_Selectable_Options__c</fullName>
    <description>For multiple choice and multi-select questions, the maximum number of options an applicant can select</description>
    <inlineHelpText>For multiple choice and multi-select questions, the maximum number of options an applicant can select</inlineHelpText>
    <label>Max Selectable Options</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Min_Selectable_Options__c.field-meta.xml
<CustomField>
    <fullName>Min_Selectable_Options__c</fullName>
    <description>For multiple choice and multi-select questions, the minimum number of options an applicant can select</description>
    <inlineHelpText>For multiple choice and multi-select questions, the minimum number of options an applicant can select</inlineHelpText>
    <label>Min Selectable Options</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <description>For multiple choice and multi-select questions, the available options for selection</description>
    <inlineHelpText>For multiple choice and multi-select questions, enter the values that the applicant can select from. Enter each distinct value on a separate line.</inlineHelpText>
    <label>Options</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CommunityApplicationController.cls
public with sharing class CommunityApplicationController {

    /************************************************************************
     * @param String recordId - the record id of the application
     * @return Application__c - application with nested application answers
     ************************************************************************/

    @AuraEnabled(cacheable=true)
    public static Application__c getApplication(String recordId) {
        try {
            return [
                SELECT Id, 
                       Name, 
                       Contact__c, 
                       Contact__r.FirstName, 
                       Contact__r.LastName, 
                       Program_Engagement__c, 
                       Application_Template__c, 
                       (SELECT Id, 
                               Name, 
                               Sort_Order__c, 
                               Question__c, 
                               Answer__c, 
                               Source_Question__c, 
                               Source_Question__r.Name, 
                               Source_Question__r.Field_Type__c, 
                               Source_Question__r.Help_Text__c, 
                               Source_Question__r.Min_Selectable_Options__c, 
                               Source_Question__r.Max_Selectable_Options__c, 
                               Source_Question__r.Options__c
                          FROM Application_Answers__r)
                  FROM Application__c
                 WHERE Id = :recordId
                 LIMIT 1
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}